# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.sidindonesia.rdtreport: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/opensrp
    username: postgres
    password: postgres
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker

server:
  port: 8081

# ===================================================================
# Keycloak Spring Boot properties.
# Reference is available at:
# https://www.keycloak.org/docs/latest/securing_apps/#_java_adapter_config
# ===================================================================

keycloak:
  realm: rdt-report
  resource: dev-client
  auth-server-url: https://keycloak.dev.sid-indonesia.org/auth
  public-client: true
  principal-attribute: preferred_username